// Give the Gradle daemon more heap and Metaspace in the generated android/
// project than the Expo template's -Xmx2048m -XX:MaxMetaspaceSize=512m.
//
// A single cold release build of this app on a fresh daemon already reaches
// ~94% of the 512 MiB Metaspace cap (SDK 56), and a daemon reused for a second
// build ran out and failed :expo-modules-core:compileReleaseKotlin. CI runs
// `./gradlew assembleRelease` over every module, a larger task graph than
// `expo run:android`, so leave headroom. android/ is regenerated by
// `expo prebuild`, hence a config plugin instead of a hand-edited
// gradle.properties.
const { withGradleProperties } = require('expo/config-plugins');

const JVM_ARGS = '-Xmx4096m -XX:MaxMetaspaceSize=1024m';

module.exports = function withGradleJvmArgs(config) {
  return withGradleProperties(config, (config) => {
    config.modResults = config.modResults.filter(
      (item) => !(item.type === 'property' && item.key === 'org.gradle.jvmargs')
    );
    config.modResults.push({ type: 'property', key: 'org.gradle.jvmargs', value: JVM_ARGS });
    return config;
  });
};
